export const SET_ID_TOKEN = 'SET_ID_TOKEN'
export const SET_AUTHORIZATION_CODE = 'SET_AUTHORIZATION_CODE'

export const EXCHANGING_AUTHORIZATION_CODE = 'EXCHANGING_AUTHORIZATION_CODE'
export const EXCHANGED_AUTHORIZATION_CODE = 'EXCHANGED_AUTHORIZATION_CODE'

export const EXCHANGING_REFRESH_TOKEN = 'EXCHANGING_REFRESH_TOKEN'
export const EXCHANGED_REFRESH_TOKEN = 'EXCHANGED_REFRESH_TOKEN'

export const LOGOUT = 'LOGOUT'

export const READY_TO_CONNECT = 'READY_TO_CONNECT'
export const CONNECTED = 'CONNECTED'

export const RESOURCES_RETRIEVED = 'RESOURCES_RETRIEVED'

export const CONFIGURE_COMPONENTS = 'CONFIGURE_COMPONENTS'
export const INSTANCES_COMPONENTS_DISTRIBUTED = 'INSTANCES_COMPONENTS_DISTRIBUTED'

export const SET_VALUES = 'SET_VALUES'

export const SET_EXPRESSION = 'SET_EXPRESSION'
export const CLEAR_EXPRESSION = 'CLEAR_EXPRESSION'
export const DELETE_LAST_EXPRESSION_ENTRY = 'DELETE_LAST_EXPRESSION_ENTRY'
export const EVALUATE_EXPRESSION = 'EVALUATE_EXPRESSION'