export const SET_AUTHORIZATION_CODE = 'SET_AUTHORIZATION_CODE'

export const EXCHANGING_AUTHORIZATION_CODE = 'EXCHANGING_AUTHORIZATION_CODE'
export const EXCHANGED_AUTHORIZATION_CODE = 'EXCHANGED_AUTHORIZATION_CODE'

export const EXCHANGING_REFRESH_TOKEN = 'EXCHANGING_REFRESH_TOKEN'
export const EXCHANGED_REFRESH_TOKEN = 'EXCHANGED_REFRESH_TOKEN'

export const REQUEST_USER_INFO = 'REQUEST_USER_INFO'
export const RECEIVED_USER_INFO = 'RECEIVED_USER_INFO'

export const SET_EXPRESSION = 'SET_EXPRESSION'
export const CLEAR_EXPRESSION = 'CLEAR_EXPRESSION'
export const DELETE_LAST_EXPRESSION_ENTRY = 'DELETE_LAST_EXPRESSION_ENTRY'
export const EVALUATE_EXPRESSION = 'EVALUATE_EXPRESSION'